Ejercicios Tema 4 Jana Montero Perales
UnirCs/BBDDA-PER10373-2425 pull request #107
Opened 2024-11-23 16:50 UTC by jmp-unir

2024-11-25 00:28 UTC, UnirCs requested changes
Es necesario subir el proyecto como tal Jana, no el submódulo :(
Tal como lo has hecho para T5

2024-11-25 06:09 UTC, jmp-unir commented
> Es necesario subir el proyecto como tal Jana, no el submódulo :( Tal como lo has hecho para T5

No acabo de entender, he incluído el proyecto completo (pom, gitignore y README incluidos), como he hecho con el tema 5, salvo que he eliminado archivos que no se utilizaban en el ejercicio, como unirEmployees.csv

2024-11-26 09:24 UTC, UnirCs commented
Algo debes de haber incluido de forma diferente, no se puede acceder a los archivos de ese modulo (solo tienes acceso tu), probablemente se te colaria algun .git

2024-11-28 09:22 UTC, jmp-unir commented
> Algo debes de haber incluido de forma diferente, no se puede acceder a los archivos de ese modulo (solo tienes acceso tu), probablemente se te colaria algun .git

Pues es que no veo nada diferente (ni un .git ni nada). Por si acaso he borrado el directorio entero y lo he vuelto a añadir. A ver si ayuda

2024-11-30 23:18 UTC, UnirCs approved these changes
Ahora esta estupendo!

2024-11-30 23:19 UTC, merged