MiPrimerPullRequest
UnirCs/BBDDA-PER10373-2425 pull request #34
Opened 2024-11-02 20:49 UTC by gilbertoeh

2024-11-03 11:11 UTC, UnirCs requested changes
Hola Gilberto, los archivos que has subido (2) están bien ubicados en tu carpeta, pero no son los que pido para la entrega del T1.
Revisa las instrucciones de los readme's del repositorio global, de cada tema.

2024-11-03 14:49 UTC, gilbertoeh commented
Si profe era una prueba. 
![helloMySQL](https://github.com/user-attachments/assets/637eb79a-aca6-49ca-9741-afac207aabe4)

2024-11-03 14:49 UTC, gilbertoeh commented
Estoy aprendiendo a usar GithHub, aun estoy descargando Oracle

2024-11-03 17:26 UTC, UnirCs commented
Estupendo sin problema, avisame por aqui cuando este todo para revisar

2024-11-04 15:20 UTC, UnirCs approved these changes
OK!

2024-11-04 15:20 UTC, merged