Entrega ejercicios Tema 2
UnirCs/BBDDA-PER10373-2425 pull request #94
Opened 2024-11-18 18:17 UTC by i40130

Incluye consultas SQL y ejercicios de JDBC para el Tema 2

2024-11-18 23:43 UTC, UnirCs commented on .zshrc
Debe eliminarse de la PR este archivo

2024-11-18 23:43 UTC, UnirCs commented on Tema_1/Ivan_Orlando_Hernandez_Santana/helloOracle.png
Modificas el archivo de otra persona

2024-11-18 23:44 UTC, UnirCs requested changes
La PR toca archivos no permitidos.
Los ejercicios estan bien, en el t3 recuerda que la forma mas eficiente de proceder es insertar mientras lees en bloques, no leer todo y luego insertar todo. segun el tamaño de los ficheros podrias quedarte sin memoria.

2024-11-19 08:20 UTC, i40130 commented on .zshrc
Creo que ya lo he eliminado

2024-11-19 08:21 UTC, i40130 commented on Tema_1/Ivan_Orlando_Hernandez_Santana/helloOracle.png
He revertido los cambios para no tocar este archivo. Pido disculpas, no se que habrá podido pasar y como se me coló este archivo del compañero

2024-11-19 08:44 UTC, UnirCs approved these changes
OK! Ten en cuenta que solo se ha subido el tema 2, antes tenias el tema 3 y creo que lo has revertido

2024-11-19 08:45 UTC, merged